//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_Bocadillo_Restaurante", "Restaurante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Restaurante), "Bocadillo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.Bocadillo), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Bocadillo", "Bocadillo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Bocadillo), "BocadilloIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.BocadilloIngrediente), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Bocadillo", "Bocadillo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Bocadillo), "VotosBocadillo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.VotosBocadillo), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Ingrediente", "Ingrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Ingrediente), "BocadilloIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.BocadilloIngrediente), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Usuario), "BocadilloIngrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.BocadilloIngrediente), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_Restaurante_Ciudad", "Ciudad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Ciudad), "Restaurante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.Restaurante), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_Ingrediente_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Usuario), "Ingrediente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.Ingrediente), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Restaurante", "Restaurante", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Restaurante), "VotosRestaurante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.VotosRestaurante), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Usuario), "VotosBocadillo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.VotosBocadillo), true)]
[assembly: EdmRelationshipAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PanizoMVC.Usuario), "VotosRestaurante", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PanizoMVC.VotosRestaurante), true)]

#endregion

namespace PanizoMVC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntrepanDB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntrepanDB object using the connection string found in the 'EntrepanDB' section of the application configuration file.
        /// </summary>
        public EntrepanDB() : base("name=EntrepanDB", "EntrepanDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntrepanDB object.
        /// </summary>
        public EntrepanDB(string connectionString) : base(connectionString, "EntrepanDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntrepanDB object.
        /// </summary>
        public EntrepanDB(EntityConnection connection) : base(connection, "EntrepanDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bocadillo> Bocadillos
        {
            get
            {
                if ((_Bocadillos == null))
                {
                    _Bocadillos = base.CreateObjectSet<Bocadillo>("Bocadillos");
                }
                return _Bocadillos;
            }
        }
        private ObjectSet<Bocadillo> _Bocadillos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BocadilloIngrediente> BocadilloIngredientes
        {
            get
            {
                if ((_BocadilloIngredientes == null))
                {
                    _BocadilloIngredientes = base.CreateObjectSet<BocadilloIngrediente>("BocadilloIngredientes");
                }
                return _BocadilloIngredientes;
            }
        }
        private ObjectSet<BocadilloIngrediente> _BocadilloIngredientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ciudad> Ciudades
        {
            get
            {
                if ((_Ciudades == null))
                {
                    _Ciudades = base.CreateObjectSet<Ciudad>("Ciudades");
                }
                return _Ciudades;
            }
        }
        private ObjectSet<Ciudad> _Ciudades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingrediente> Ingredientes
        {
            get
            {
                if ((_Ingredientes == null))
                {
                    _Ingredientes = base.CreateObjectSet<Ingrediente>("Ingredientes");
                }
                return _Ingredientes;
            }
        }
        private ObjectSet<Ingrediente> _Ingredientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Restaurante> Restaurantes
        {
            get
            {
                if ((_Restaurantes == null))
                {
                    _Restaurantes = base.CreateObjectSet<Restaurante>("Restaurantes");
                }
                return _Restaurantes;
            }
        }
        private ObjectSet<Restaurante> _Restaurantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VotosBocadillo> VotosBocadillos
        {
            get
            {
                if ((_VotosBocadillos == null))
                {
                    _VotosBocadillos = base.CreateObjectSet<VotosBocadillo>("VotosBocadillos");
                }
                return _VotosBocadillos;
            }
        }
        private ObjectSet<VotosBocadillo> _VotosBocadillos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VotosRestaurante> VotosRestaurantes
        {
            get
            {
                if ((_VotosRestaurantes == null))
                {
                    _VotosRestaurantes = base.CreateObjectSet<VotosRestaurante>("VotosRestaurantes");
                }
                return _VotosRestaurantes;
            }
        }
        private ObjectSet<VotosRestaurante> _VotosRestaurantes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bocadillos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBocadillos(Bocadillo bocadillo)
        {
            base.AddObject("Bocadillos", bocadillo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BocadilloIngredientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBocadilloIngredientes(BocadilloIngrediente bocadilloIngrediente)
        {
            base.AddObject("BocadilloIngredientes", bocadilloIngrediente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ciudades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCiudades(Ciudad ciudad)
        {
            base.AddObject("Ciudades", ciudad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredientes(Ingrediente ingrediente)
        {
            base.AddObject("Ingredientes", ingrediente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Restaurantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestaurantes(Restaurante restaurante)
        {
            base.AddObject("Restaurantes", restaurante);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VotosBocadillos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVotosBocadillos(VotosBocadillo votosBocadillo)
        {
            base.AddObject("VotosBocadillos", votosBocadillo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VotosRestaurantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVotosRestaurantes(VotosRestaurante votosRestaurante)
        {
            base.AddObject("VotosRestaurantes", votosRestaurante);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="Bocadillo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bocadillo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bocadillo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idRestaurante">Initial value of the IdRestaurante property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static Bocadillo CreateBocadillo(global::System.Int32 id, global::System.Int32 idRestaurante, global::System.String nombre, global::System.String descripcion, global::System.Decimal precio, global::System.DateTime fechaCreacion)
        {
            Bocadillo bocadillo = new Bocadillo();
            bocadillo.Id = id;
            bocadillo.IdRestaurante = idRestaurante;
            bocadillo.Nombre = nombre;
            bocadillo.Descripcion = descripcion;
            bocadillo.Precio = precio;
            bocadillo.FechaCreacion = fechaCreacion;
            return bocadillo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRestaurante
        {
            get
            {
                return _IdRestaurante;
            }
            set
            {
                OnIdRestauranteChanging(value);
                ReportPropertyChanging("IdRestaurante");
                _IdRestaurante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdRestaurante");
                OnIdRestauranteChanged();
            }
        }
        private global::System.Int32 _IdRestaurante;
        partial void OnIdRestauranteChanging(global::System.Int32 value);
        partial void OnIdRestauranteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Decimal _Precio;
        partial void OnPrecioChanging(global::System.Decimal value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Bocadillo_Restaurante", "Restaurante")]
        public Restaurante Restaurante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Restaurante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Restaurante").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restaurante> RestauranteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Restaurante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restaurante>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Restaurante", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Bocadillo", "BocadilloIngrediente")]
        public EntityCollection<BocadilloIngrediente> BocadilloIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "BocadilloIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "BocadilloIngrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Bocadillo", "VotosBocadillo")]
        public EntityCollection<VotosBocadillo> VotosBocadillo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VotosBocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "VotosBocadillo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VotosBocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "VotosBocadillo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="BocadilloIngrediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BocadilloIngrediente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BocadilloIngrediente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="idBocadillo">Initial value of the IdBocadillo property.</param>
        /// <param name="idIngrediente">Initial value of the IdIngrediente property.</param>
        public static BocadilloIngrediente CreateBocadilloIngrediente(global::System.Int32 id, global::System.Int32 idUsuario, global::System.Int32 idBocadillo, global::System.Int32 idIngrediente)
        {
            BocadilloIngrediente bocadilloIngrediente = new BocadilloIngrediente();
            bocadilloIngrediente.Id = id;
            bocadilloIngrediente.IdUsuario = idUsuario;
            bocadilloIngrediente.IdBocadillo = idBocadillo;
            bocadilloIngrediente.IdIngrediente = idIngrediente;
            return bocadilloIngrediente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdBocadillo
        {
            get
            {
                return _IdBocadillo;
            }
            set
            {
                OnIdBocadilloChanging(value);
                ReportPropertyChanging("IdBocadillo");
                _IdBocadillo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdBocadillo");
                OnIdBocadilloChanged();
            }
        }
        private global::System.Int32 _IdBocadillo;
        partial void OnIdBocadilloChanging(global::System.Int32 value);
        partial void OnIdBocadilloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdIngrediente
        {
            get
            {
                return _IdIngrediente;
            }
            set
            {
                OnIdIngredienteChanging(value);
                ReportPropertyChanging("IdIngrediente");
                _IdIngrediente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdIngrediente");
                OnIdIngredienteChanged();
            }
        }
        private global::System.Int32 _IdIngrediente;
        partial void OnIdIngredienteChanging(global::System.Int32 value);
        partial void OnIdIngredienteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Bocadillo", "Bocadillo")]
        public Bocadillo Bocadillo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "Bocadillo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "Bocadillo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bocadillo> BocadilloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "Bocadillo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_BocadilloIngrediente_Bocadillo", "Bocadillo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Ingrediente", "Ingrediente")]
        public Ingrediente Ingrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "Ingrediente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "Ingrediente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingrediente> IngredienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "Ingrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "Ingrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="Ciudad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ciudad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ciudad object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Ciudad CreateCiudad(global::System.Int32 id, global::System.String nombre)
        {
            Ciudad ciudad = new Ciudad();
            ciudad.Id = id;
            ciudad.Nombre = nombre;
            return ciudad;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Restaurante_Ciudad", "Restaurante")]
        public EntityCollection<Restaurante> Restaurante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Restaurante>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Restaurante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Restaurante>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Restaurante", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="Ingrediente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingrediente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingrediente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static Ingrediente CreateIngrediente(global::System.Int32 id, global::System.Int32 idUsuario, global::System.String nombre, global::System.String descripcion, global::System.DateTime fechaCreacion)
        {
            Ingrediente ingrediente = new Ingrediente();
            ingrediente.Id = id;
            ingrediente.IdUsuario = idUsuario;
            ingrediente.Nombre = nombre;
            ingrediente.Descripcion = descripcion;
            ingrediente.FechaCreacion = fechaCreacion;
            return ingrediente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Ingrediente", "BocadilloIngrediente")]
        public EntityCollection<BocadilloIngrediente> BocadilloIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "BocadilloIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Ingrediente", "BocadilloIngrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Ingrediente_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="Restaurante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Restaurante : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Restaurante object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idCiudad">Initial value of the IdCiudad property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="cP">Initial value of the CP property.</param>
        /// <param name="telefono">Initial value of the Telefono property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static Restaurante CreateRestaurante(global::System.Int32 id, global::System.Int32 idCiudad, global::System.String nombre, global::System.String direccion, global::System.String cP, global::System.String telefono, global::System.String descripcion, global::System.DateTime fechaCreacion)
        {
            Restaurante restaurante = new Restaurante();
            restaurante.Id = id;
            restaurante.IdCiudad = idCiudad;
            restaurante.Nombre = nombre;
            restaurante.Direccion = direccion;
            restaurante.CP = cP;
            restaurante.Telefono = telefono;
            restaurante.Descripcion = descripcion;
            restaurante.FechaCreacion = fechaCreacion;
            return restaurante;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCiudad
        {
            get
            {
                return _IdCiudad;
            }
            set
            {
                OnIdCiudadChanging(value);
                ReportPropertyChanging("IdCiudad");
                _IdCiudad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCiudad");
                OnIdCiudadChanged();
            }
        }
        private global::System.Int32 _IdCiudad;
        partial void OnIdCiudadChanging(global::System.Int32 value);
        partial void OnIdCiudadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CP
        {
            get
            {
                return _CP;
            }
            set
            {
                OnCPChanging(value);
                ReportPropertyChanging("CP");
                _CP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CP");
                OnCPChanged();
            }
        }
        private global::System.String _CP;
        partial void OnCPChanging(global::System.String value);
        partial void OnCPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Web
        {
            get
            {
                return _Web;
            }
            set
            {
                OnWebChanging(value);
                ReportPropertyChanging("Web");
                _Web = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Web");
                OnWebChanged();
            }
        }
        private global::System.String _Web;
        partial void OnWebChanging(global::System.String value);
        partial void OnWebChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Bocadillo_Restaurante", "Bocadillo")]
        public EntityCollection<Bocadillo> Bocadillo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bocadillo>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Bocadillo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bocadillo>("DB_37268_panizoModel.FK_Bocadillo_Restaurante", "Bocadillo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Restaurante_Ciudad", "Ciudad")]
        public Ciudad Ciudad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Ciudad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Ciudad").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ciudad> CiudadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ciudad>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Ciudad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ciudad>("DB_37268_panizoModel.FK_Restaurante_Ciudad", "Ciudad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Restaurante", "VotosRestaurante")]
        public EntityCollection<VotosRestaurante> VotosRestaurante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VotosRestaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "VotosRestaurante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VotosRestaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "VotosRestaurante", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        /// <param name="isAdmin">Initial value of the IsAdmin property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.DateTime fechaCreacion, global::System.Boolean isAdmin)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.FechaCreacion = fechaCreacion;
            usuario.IsAdmin = isAdmin;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                OnNickChanging(value);
                ReportPropertyChanging("Nick");
                _Nick = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nick");
                OnNickChanged();
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterAccessSecret
        {
            get
            {
                return _TwitterAccessSecret;
            }
            set
            {
                OnTwitterAccessSecretChanging(value);
                ReportPropertyChanging("TwitterAccessSecret");
                _TwitterAccessSecret = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterAccessSecret");
                OnTwitterAccessSecretChanged();
            }
        }
        private global::System.String _TwitterAccessSecret;
        partial void OnTwitterAccessSecretChanging(global::System.String value);
        partial void OnTwitterAccessSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterAccessKey
        {
            get
            {
                return _TwitterAccessKey;
            }
            set
            {
                OnTwitterAccessKeyChanging(value);
                ReportPropertyChanging("TwitterAccessKey");
                _TwitterAccessKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterAccessKey");
                OnTwitterAccessKeyChanged();
            }
        }
        private global::System.String _TwitterAccessKey;
        partial void OnTwitterAccessKeyChanging(global::System.String value);
        partial void OnTwitterAccessKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterUserId
        {
            get
            {
                return _TwitterUserId;
            }
            set
            {
                OnTwitterUserIdChanging(value);
                ReportPropertyChanging("TwitterUserId");
                _TwitterUserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterUserId");
                OnTwitterUserIdChanged();
            }
        }
        private global::System.String _TwitterUserId;
        partial void OnTwitterUserIdChanging(global::System.String value);
        partial void OnTwitterUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                OnFacebookIdChanging(value);
                ReportPropertyChanging("FacebookId");
                _FacebookId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookId");
                OnFacebookIdChanged();
            }
        }
        private global::System.String _FacebookId;
        partial void OnFacebookIdChanging(global::System.String value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_BocadilloIngrediente_Usuario", "BocadilloIngrediente")]
        public EntityCollection<BocadilloIngrediente> BocadilloIngrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "BocadilloIngrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BocadilloIngrediente>("DB_37268_panizoModel.FK_BocadilloIngrediente_Usuario", "BocadilloIngrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_Ingrediente_Usuario", "Ingrediente")]
        public EntityCollection<Ingrediente> Ingrediente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingrediente>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Ingrediente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingrediente>("DB_37268_panizoModel.FK_Ingrediente_Usuario", "Ingrediente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Usuario", "VotosBocadillo")]
        public EntityCollection<VotosBocadillo> VotosBocadillo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VotosBocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "VotosBocadillo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VotosBocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "VotosBocadillo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Usuario", "VotosRestaurante")]
        public EntityCollection<VotosRestaurante> VotosRestaurante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VotosRestaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "VotosRestaurante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VotosRestaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "VotosRestaurante", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="VotosBocadillo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VotosBocadillo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VotosBocadillo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="idBocadillo">Initial value of the IdBocadillo property.</param>
        /// <param name="voto">Initial value of the Voto property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static VotosBocadillo CreateVotosBocadillo(global::System.Int32 id, global::System.Int32 idUsuario, global::System.Int32 idBocadillo, global::System.Int32 voto, global::System.DateTime fechaCreacion)
        {
            VotosBocadillo votosBocadillo = new VotosBocadillo();
            votosBocadillo.Id = id;
            votosBocadillo.IdUsuario = idUsuario;
            votosBocadillo.IdBocadillo = idBocadillo;
            votosBocadillo.Voto = voto;
            votosBocadillo.FechaCreacion = fechaCreacion;
            return votosBocadillo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdBocadillo
        {
            get
            {
                return _IdBocadillo;
            }
            set
            {
                OnIdBocadilloChanging(value);
                ReportPropertyChanging("IdBocadillo");
                _IdBocadillo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdBocadillo");
                OnIdBocadilloChanged();
            }
        }
        private global::System.Int32 _IdBocadillo;
        partial void OnIdBocadilloChanging(global::System.Int32 value);
        partial void OnIdBocadilloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Voto
        {
            get
            {
                return _Voto;
            }
            set
            {
                OnVotoChanging(value);
                ReportPropertyChanging("Voto");
                _Voto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Voto");
                OnVotoChanged();
            }
        }
        private global::System.Int32 _Voto;
        partial void OnVotoChanging(global::System.Int32 value);
        partial void OnVotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Bocadillo", "Bocadillo")]
        public Bocadillo Bocadillo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "Bocadillo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "Bocadillo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bocadillo> BocadilloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "Bocadillo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bocadillo>("DB_37268_panizoModel.FK_VotosBocadillo_Bocadillo", "Bocadillo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosBocadillo_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosBocadillo_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_37268_panizoModel", Name="VotosRestaurante")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VotosRestaurante : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VotosRestaurante object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="idRestaurante">Initial value of the IdRestaurante property.</param>
        /// <param name="voto">Initial value of the Voto property.</param>
        /// <param name="comentario">Initial value of the Comentario property.</param>
        /// <param name="fechaCreacion">Initial value of the FechaCreacion property.</param>
        public static VotosRestaurante CreateVotosRestaurante(global::System.Int32 id, global::System.Int32 idUsuario, global::System.Int32 idRestaurante, global::System.Int32 voto, global::System.String comentario, global::System.DateTime fechaCreacion)
        {
            VotosRestaurante votosRestaurante = new VotosRestaurante();
            votosRestaurante.Id = id;
            votosRestaurante.IdUsuario = idUsuario;
            votosRestaurante.IdRestaurante = idRestaurante;
            votosRestaurante.Voto = voto;
            votosRestaurante.Comentario = comentario;
            votosRestaurante.FechaCreacion = fechaCreacion;
            return votosRestaurante;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRestaurante
        {
            get
            {
                return _IdRestaurante;
            }
            set
            {
                OnIdRestauranteChanging(value);
                ReportPropertyChanging("IdRestaurante");
                _IdRestaurante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdRestaurante");
                OnIdRestauranteChanged();
            }
        }
        private global::System.Int32 _IdRestaurante;
        partial void OnIdRestauranteChanging(global::System.Int32 value);
        partial void OnIdRestauranteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Voto
        {
            get
            {
                return _Voto;
            }
            set
            {
                OnVotoChanging(value);
                ReportPropertyChanging("Voto");
                _Voto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Voto");
                OnVotoChanged();
            }
        }
        private global::System.Int32 _Voto;
        partial void OnVotoChanging(global::System.Int32 value);
        partial void OnVotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Restaurante", "Restaurante")]
        public Restaurante Restaurante
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "Restaurante").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "Restaurante").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restaurante> RestauranteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "Restaurante");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restaurante>("DB_37268_panizoModel.FK_VotosRestaurante_Restaurante", "Restaurante", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_37268_panizoModel", "FK_VotosRestaurante_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DB_37268_panizoModel.FK_VotosRestaurante_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
